<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class LocalProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Naturea Acne Treatment Serum',
                'description' => 'Serum intensif untuk mengatasi jerawat aktif, meredakan kemerahan, dan mengontrol produksi minyak berlebih tanpa membuat kulit kering.',
                'price' => 119000,
                'stock' => 80,
                'category' => 'Serum',
                'image_url' => 'images/products/acne-treatment-serum.jpeg',
                'ingredients' => ['Salicylic Acid 2%', 'Niacinamide 4%', 'Tea Tree Oil', 'Centella Asiatica'],
                'skin_type' => ['Berjerawat', 'Berminyak', 'Sensitif', 'Kombinasi'],
                'skin_type_not_suitable' => 'Tidak disarankan untuk kulit sangat kering yang mengelupas.',
                'usage_instructions' => 'Teteskan 2-3 tetes serum pada wajah yang bersih di pagi dan malam hari. Tepuk lembut hingga meresap.',
                'benefits' => 'Mengurangi jerawat dalam 3 hari, meredakan kemerahan, dan memudarkan bekas jerawat.',
                'bpom_number' => 'NA18240104321',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Barrier Repair Cream',
                'description' => 'Krim pelembap intensif yang memulihkan dan memperkuat pertahanan alami kulit (skin barrier) serta memberikan kelembapan ekstra.',
                'price' => 135000,
                'stock' => 90,
                'category' => 'Moisturizer',
                'image_url' => 'images/products/barrier-repair-cream.jpeg',
                'ingredients' => ['Ceramide NP', 'Hyaluronic Acid', 'Panthenol', 'Squalane'],
                'skin_type' => ['Kering', 'Sensitif', 'Normal', 'Kombinasi'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Oleskan merata pada wajah dan leher setelah menggunakan toner atau serum. Gunakan pagi dan malam hari.',
                'benefits' => 'Memperbaiki skin barrier yang rusak, mengunci kelembapan hingga 48 jam, dan mengurangi sensitivitas kulit.',
                'bpom_number' => 'NA18240104322',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Brightening Mask',
                'description' => 'Masker bilas dengan tekstur mewah yang menutrisi kulit, mengangkat sel kulit mati, dan mengembalikan kecerahan alami wajah.',
                'price' => 85000,
                'stock' => 120,
                'category' => 'Mask',
                'image_url' => 'images/products/brightening-mask.jpeg',
                'ingredients' => ['Kaolin Clay', 'Licorice Extract', 'Vitamin C', 'Alpha Arbutin'],
                'skin_type' => ['Normal', 'Berminyak', 'Kombinasi'],
                'skin_type_not_suitable' => 'Gunakan hati-hati pada kulit yang sangat sensitif.',
                'usage_instructions' => 'Oleskan masker pada wajah yang bersih, hindari area mata dan mulut. Diamkan selama 10-15 menit lalu bilas dengan air hangat.',
                'benefits' => 'Mencerahkan kulit kusam secara instan, mengecilkan tampilan pori-pori, dan menghaluskan tekstur kulit.',
                'bpom_number' => 'NA18240200888',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Calming Toner',
                'description' => 'Toner hidrasi ringan yang diformulasikan khusus untuk menenangkan kulit yang teriritasi, meredakan kemerahan, dan menyeimbangkan pH kulit.',
                'price' => 95000,
                'stock' => 150,
                'category' => 'Toner',
                'image_url' => 'images/products/calming-toner.jpeg',
                'ingredients' => ['Centella Asiatica 75%', 'Chamomile Extract', 'Calendula Oil', 'Allantoin'],
                'skin_type' => ['Sensitif', 'Normal', 'Berjerawat', 'Kombinasi'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Tuangkan secukupnya pada kapas atau telapak tangan yang bersih, lalu usapkan atau tepuk-tepuk lembut ke seluruh wajah setelah mencuci muka.',
                'benefits' => 'Meredakan iritasi, memberikan hidrasi instan, dan mempersiapkan kulit untuk skincare selanjutnya.',
                'bpom_number' => 'NA18241201501',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Eye Repair Cream',
                'description' => 'Krim khusus area mata yang merawat elastisitas kulit halus di sekitar mata, memudarkan lingkaran hitam, dan mengurangi garis halus.',
                'price' => 110000,
                'stock' => 60,
                'category' => 'Treatment',
                'image_url' => 'images/products/eye-repair-cream.jpeg',
                'ingredients' => ['Caffeine', 'Peptides', 'Niacinamide', 'Cucumber Extract'],
                'skin_type' => ['Semua Jenis Kulit'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Oleskan sedikit krim di sekitar area mata dengan jari manis. Tepuk lembut hingga meresap sempurna. Gunakan pagi dan malam.',
                'benefits' => 'Mengurangi mata sembab (puffiness), menyamarkan lingkaran hitam (mata panda), dan menghaluskan garis kerutan.',
                'bpom_number' => 'NA18242000555',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Soothing Face Mist',
                'description' => 'Penyegar wajah praktis yang memberikan kelembapan instan dan perlindungan antioksidan di mana saja dan kapan saja.',
                'price' => 65000,
                'stock' => 200,
                'category' => 'Toner',
                'image_url' => 'images/products/face-mist.jpeg',
                'ingredients' => ['Aloe Vera Extract', 'Rose Water', 'Glycerin', 'Green Tea Extract'],
                'skin_type' => ['Semua Jenis Kulit'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Semprotkan pada wajah dengan jarak 15-20 cm. Dapat digunakan sebelum/sesudah makeup atau kapan pun kulit terasa kering.',
                'benefits' => 'Menyegarkan kulit lelah, menenangkan kemerahan karena sinar matahari, dan menjaga hidrasi kulit.',
                'bpom_number' => 'NA18241208990',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Gentle Soothing Cleanser',
                'description' => 'Pembersih wajah ber-pH seimbang yang membersihkan kotoran dan minyak berlebih tanpa merusak skin barrier alami kulit.',
                'price' => 79000,
                'stock' => 140,
                'category' => 'Cleanser',
                'image_url' => 'images/products/gentle-shooting-cleanser.jpeg',
                'ingredients' => ['Oat Extract', 'Chamomile Extract', 'Panthenol', 'Mild Surfactants'],
                'skin_type' => ['Sensitif', 'Normal', 'Kering', 'Berjerawat', 'Kombinasi'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Basahi wajah dengan air, busakan pembersih di telapak tangan, pijat lembut ke seluruh wajah dengan gerakan melingkar, lalu bilas hingga bersih.',
                'benefits' => 'Membersihkan pori-pori secara lembut tanpa membuat kulit terasa kering, ketarik, atau kemerahan.',
                'bpom_number' => 'NA18241209911',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Glass Skin Serum',
                'description' => 'Serum pencerah konsentrasi tinggi untuk menghasilkan efek kulit berkilau sehat dan transparan bagai kaca (glass skin effect).',
                'price' => 145000,
                'stock' => 70,
                'category' => 'Serum',
                'image_url' => 'images/products/glass-skin-serum.jpeg',
                'ingredients' => ['Niacinamide 10%', 'Hyaluronic Acid 2%', 'Galactomyces Ferment Filtrate', 'Arbutin'],
                'skin_type' => ['Normal', 'Kering', 'Berminyak', 'Kombinasi'],
                'skin_type_not_suitable' => 'Gunakan patch test terlebih dahulu untuk kulit yang sangat hipersensitif.',
                'usage_instructions' => 'Gunakan 2-3 tetes pada wajah bersih di pagi dan malam hari sebelum menggunakan pelembap.',
                'benefits' => 'Mencerahkan wajah secara merata, menyamarkan pori-pori besar, dan memberikan kilau dewy alami.',
                'bpom_number' => 'NA18241900101',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Glow Moisturizer',
                'description' => 'Pelembap harian bertekstur gel ringan yang mencerahkan kulit secara efektif sembari memberikan hidrasi yang tahan lama.',
                'price' => 125000,
                'stock' => 85,
                'category' => 'Moisturizer',
                'image_url' => 'images/products/glow-moist.jpeg',
                'ingredients' => ['Niacinamide 5%', 'Hyaluronic Acid', 'Shea Butter', 'Ginseng Extract'],
                'skin_type' => ['Normal', 'Berminyak', 'Kombinasi'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Oleskan secukupnya secara merata pada seluruh wajah dan leher setelah dibersihkan. Gunakan pagi dan malam.',
                'benefits' => 'Meningkatkan kecerahan kulit, melembapkan tanpa rasa lengket, dan membuat kulit tampak glowing sehat.',
                'bpom_number' => 'NA18240103333',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Mild Cleanser',
                'description' => 'Sabun cuci muka formula lembut yang efektif mengangkat sisa riasan wajah dan kotoran tanpa memicu iritasi kulit.',
                'price' => 72000,
                'stock' => 160,
                'category' => 'Cleanser',
                'image_url' => 'images/products/mild-cleanser.jpeg',
                'ingredients' => ['Tea Tree Water', 'Glycerin', 'Aloe Vera Juice'],
                'skin_type' => ['Normal', 'Berminyak', 'Berjerawat', 'Kombinasi'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Basahi wajah, pijatkan cleanser ke seluruh wajah secara lembut, bilas bersih dengan air dingin.',
                'benefits' => 'Membersihkan sisa sebum dan kotoran dengan kelembutan ekstra bagi kulit.',
                'bpom_number' => 'NA18241200012',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Night Cleanser',
                'description' => 'Pembersih wajah malam hari yang diformulasikan khusus untuk detoksifikasi kulit dan membersihkan pori-pori dari sisa polusi harian.',
                'price' => 79000,
                'stock' => 100,
                'category' => 'Cleanser',
                'image_url' => 'images/products/night-cleanser.jpeg',
                'ingredients' => ['Activated Charcoal', 'Salicylic Acid', 'Aloe Vera Extract', 'Rosemary Oil'],
                'skin_type' => ['Berminyak', 'Berjerawat', 'Kombinasi'],
                'skin_type_not_suitable' => 'Tidak direkomendasikan untuk kulit sangat kering/mengelupas.',
                'usage_instructions' => 'Gunakan di malam hari sebagai bagian dari rutinitas double cleansing. Pijat lembut pada wajah basah lalu bilas hangat.',
                'benefits' => 'Mengangkat partikel polusi mikro, mencegah komedo terbentuk, dan mendetoks pori-pori.',
                'bpom_number' => 'NA18241200045',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Repair Toner',
                'description' => 'Toner bergizi yang merangsang regenerasi sel kulit baru dan menenangkan barrier kulit yang sedang teriritasi atau kemerahan.',
                'price' => 99000,
                'stock' => 110,
                'category' => 'Toner',
                'image_url' => 'images/products/repair-toner.jpeg',
                'ingredients' => ['Bifida Ferment Lysate 10%', 'Centella Asiatica', 'Hyaluronic Acid', 'Panthenol'],
                'skin_type' => ['Semua Jenis Kulit', 'Sensitif'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Aplikasikan toner menggunakan telapak tangan langsung atau tuangkan ke kapas. Usapkan lembut ke seluruh area wajah.',
                'benefits' => 'Mempercepat perbaikan sel kulit baru, menghaluskan kulit kasar, dan mengenyalkan wajah.',
                'bpom_number' => 'NA18241201999',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Retinol Renewal Serum',
                'description' => 'Serum anti-aging dengan kandungan retinol mikro enkapsulasi yang lembut namun efektif merevitalisasi sel kulit dan mengurangi garis halus.',
                'price' => 149000,
                'stock' => 50,
                'category' => 'Serum',
                'image_url' => 'images/products/retinol-serum.jpeg',
                'ingredients' => ['Encapsulated Retinol 1%', 'Ceramide NP', 'Allantoin', 'Hyaluronic Acid'],
                'skin_type' => ['Normal', 'Berminyak', 'Kombinasi'],
                'skin_type_not_suitable' => 'Tidak untuk wanita hamil atau menyusui. Hindari kulit sensitif yang sedang meradang.',
                'usage_instructions' => 'Gunakan HANYA di malam hari. Aplikasikan 2-3 tetes pada kulit kering setelah toner. Gunakan sunscreen di pagi harinya.',
                'benefits' => 'Mengurangi garis halus dan kerutan, menyamarkan noda penuaan, dan meremajakan tekstur kulit.',
                'bpom_number' => 'NA18241900333',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Soothing Serum',
                'description' => 'Serum penenang konsentrasi tinggi yang meredakan inflamasi kulit akibat breakout, polusi, maupun paparan sinar matahari.',
                'price' => 115000,
                'stock' => 80,
                'category' => 'Serum',
                'image_url' => 'images/products/shooting-serum.jpeg',
                'ingredients' => ['Centella Asiatica 85%', 'Madecassoside', 'Panthenol 5%', 'Allantoin'],
                'skin_type' => ['Sensitif', 'Normal', 'Berjerawat', 'Kombinasi'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Usapkan secara merata pada seluruh area wajah pagi dan malam setelah menggunakan toner hidrasi.',
                'benefits' => 'Menghilangkan rasa gatal akibat iritasi, meredakan peradangan jerawat, dan meredakan kulit terbakar matahari.',
                'bpom_number' => 'NA18241900456',
                'is_bundle' => false,
            ],
            [
                'name' => 'Naturea Sleeping Mask Night',
                'description' => 'Masker tidur tanpa dibilas yang melembapkan secara mendalam semalaman agar bangun dengan kulit yang segar dan terhidrasi.',
                'price' => 99000,
                'stock' => 75,
                'category' => 'Mask',
                'image_url' => 'images/products/sleeping-mask-night.jpeg',
                'ingredients' => ['Snail Secretion Filtrate', 'Ceramide NP', 'Aloe Vera Extract', 'Niacinamide'],
                'skin_type' => ['Kering', 'Sensitif', 'Normal', 'Kombinasi'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Sebagai langkah terakhir rutinitas malam. Oleskan tebal secara merata pada wajah sebelum tidur. Diamkan semalaman dan bilas keesokan harinya.',
                'benefits' => 'Mencegah kehilangan air saat tidur, melembutkan kulit kering, dan mengembalikan kesegaran wajah di pagi hari.',
                'bpom_number' => 'NA18240200900',
                'is_bundle' => false,
            ],
            
            // ─── PAKET / BUNDLE PRODUCTS ─────────────────────────────────
            [
                'name' => 'Naturea Paket 2: Brightening Glow Set',
                'description' => 'Paket perawatan pencerah harian eksklusif. Terdiri dari Gentle Soothing Cleanser, Calming Toner, dan Glass Skin Serum untuk mencerahkan wajah kusam.',
                'price' => 289000,
                'stock' => 40,
                'category' => 'Bundle',
                'image_url' => 'images/products/paket-2-paket-brightening.jpeg',
                'ingredients' => ['Niacinamide', 'Alpha Arbutin', 'Vitamin C', 'Oat Extract'],
                'skin_type' => ['Normal', 'Berminyak', 'Kombinasi'],
                'skin_type_not_suitable' => 'Gunakan patch test untuk kulit sangat sensitif.',
                'usage_instructions' => 'Gunakan Cleanser untuk cuci muka, ikuti dengan Calming Toner, lalu apply Glass Skin Serum secara teratur pagi dan malam.',
                'benefits' => 'Wajah tampak lebih cerah bersinar dan merata dalam 14 hari.',
                'bpom_number' => 'NA-BUND-BRIGHT2',
                'is_bundle' => true,
                'bundle_discount' => 10.00, // 10%
            ],
            [
                'name' => 'Naturea Paket 3: Hydration Boost Set',
                'description' => 'Solusi lengkap bagi kulit kering dan dehidrasi. Terdiri dari Repair Toner, Barrier Repair Cream, dan Sleeping Mask Night.',
                'price' => 299000,
                'stock' => 30,
                'category' => 'Bundle',
                'image_url' => 'images/products/paket-3-hydration-bost.jpeg',
                'ingredients' => ['Ceramide NP', 'Hyaluronic Acid 2%', 'Bifida Ferment', 'Aloe Vera Juice'],
                'skin_type' => ['Kering', 'Sensitif', 'Normal'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Gunakan Repair Toner setelah cuci muka, lanjutkan dengan Barrier Repair Cream di pagi/malam hari, tambahkan Sleeping Mask di malam hari.',
                'benefits' => 'Menghidrasi kulit secara instan hingga ke lapisan dalam dan mengunci kelembapan.',
                'bpom_number' => 'NA-BUND-HYDRA3',
                'is_bundle' => true,
                'bundle_discount' => 12.00, // 12%
            ],
            [
                'name' => 'Naturea Paket 4: Acne Care Set',
                'description' => 'Rangkaian pembersih dan perawatan intensif jerawat. Berisi Mild Cleanser, Acne Treatment Serum, dan Soothing Serum.',
                'price' => 269000,
                'stock' => 50,
                'category' => 'Bundle',
                'image_url' => 'images/products/paket-4-acne-care.jpeg',
                'ingredients' => ['Salicylic Acid 2%', 'Tea Tree Oil', 'Centella Asiatica 85%'],
                'skin_type' => ['Berjerawat', 'Berminyak', 'Sensitif', 'Kombinasi'],
                'skin_type_not_suitable' => 'Tidak disarankan untuk kulit kering parah.',
                'usage_instructions' => 'Cuci muka dengan Mild Cleanser, gunakan Acne Serum pada jerawat aktif, lalu aplikasikan Soothing Serum ke seluruh wajah untuk menenangkan kulit.',
                'benefits' => 'Meredakan jerawat aktif dengan cepat dan mencegah inflamasi kulit.',
                'bpom_number' => 'NA-BUND-ACNE4',
                'is_bundle' => true,
                'bundle_discount' => 15.00,
            ],
            [
                'name' => 'Naturea Paket 5: Radiant Glow Set',
                'description' => 'Paket pencerah eksklusif premium. Terdiri dari Gentle Soothing Cleanser, Glow Moisturizer, Brightening Mask, dan Face Mist.',
                'price' => 319000,
                'stock' => 25,
                'category' => 'Bundle',
                'image_url' => 'images/products/paket-5-radiant-glow.jpeg',
                'ingredients' => ['Kaolin Clay', 'Niacinamide 5%', 'Vitamin C', 'Ginseng Extract'],
                'skin_type' => ['Normal', 'Berminyak', 'Kombinasi'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Gunakan Cleanser harian, aplikasikan Glow Moisturizer, gunakan Face Mist untuk menyegarkan, serta pakai Brightening Mask 2-3 kali seminggu.',
                'benefits' => 'Memulihkan kilau cerah alami wajah secara optimal.',
                'bpom_number' => 'NA-BUND-GLOW5',
                'is_bundle' => true,
                'bundle_discount' => 10.00,
            ],
            [
                'name' => 'Naturea Paket 8: Soothing Care Set',
                'description' => 'Paket perawatan khusus kulit sensitif dan mudah kemerahan. Berisi Gentle Soothing Cleanser, Calming Toner, dan Soothing Serum.',
                'price' => 259000,
                'stock' => 35,
                'category' => 'Bundle',
                'image_url' => 'images/products/paket-8-shooting-care.jpeg',
                'ingredients' => ['Oat Extract', 'Chamomile Extract', 'Centella Asiatica 85%', 'Madecassoside'],
                'skin_type' => ['Sensitif', 'Normal', 'Berjerawat', 'Kombinasi'],
                'skin_type_not_suitable' => null,
                'usage_instructions' => 'Gunakan langkah pembersihan dengan Gentle Cleanser, seimbangkan pH dengan Calming Toner, dan redakan sensitivitas memakai Soothing Serum.',
                'benefits' => 'Menenangkan iritasi kulit, kemerahan, dan memperkuat pertahanan kulit sensitif.',
                'bpom_number' => 'NA-BUND-SOOTH8',
                'is_bundle' => true,
                'bundle_discount' => 12.00,
            ],
            [
                'name' => 'Naturea Paket 9: Glass Skin Complete Set',
                'description' => 'Paket perawatan ultimate untuk mendapatkan kulit selembut sutra dan sebening kaca. Terdiri dari Gentle Soothing Cleanser, Repair Toner, Glass Skin Serum, Glow Moisturizer, dan Sleeping Mask.',
                'price' => 479000,
                'stock' => 20,
                'category' => 'Bundle',
                'image_url' => 'images/products/paket-9-glass-skin.jpeg',
                'ingredients' => ['Niacinamide 10%', 'Galactomyces', 'Ceramide NP', 'Hyaluronic Acid'],
                'skin_type' => ['Normal', 'Kering', 'Berminyak', 'Kombinasi'],
                'skin_type_not_suitable' => 'Gunakan patch test terlebih dahulu jika memiliki kulit ekstra sensitif.',
                'usage_instructions' => 'Lakukan pembersihan harian, aplikasikan Repair Toner, gunakan Glass Skin Serum, dan kunci kelembapan dengan Glow Moisturizer (pagi) atau Sleeping Mask (malam).',
                'benefits' => 'Dapatkan kulit halus, cerah transparan bebas flek hitam secara menyeluruh.',
                'bpom_number' => 'NA-BUND-GLASS9',
                'is_bundle' => true,
                'bundle_discount' => 15.00,
            ],
        ];

        foreach ($products as $p) {
            Product::firstOrCreate(
                ['slug' => Str::slug($p['name'])],
                array_merge($p, [
                    'type' => 'skincare',
                    'brand' => 'naturea',
                    'images' => [$p['image_url']],
                    'is_active' => true,
                    'reward_points' => 0,
                ])
            );
        }
    }
}
